### ISSUE TITLE
test suite is locale dependent - breaks on non enlish locale

### ISSUE THREAD

**Issue by oorestisime** [SimonSapin/Frozen-Flask#51]
Hello,

Thanks for the great work in frozen-flask. I have found an error in the test suite due to some locale configuration. 
When my locale is set to en_US.UTF-8 the test suite works perfectly fine. On the other hand when it is set to fr_CH.UTF-8 then 60 tests fail because of this same error:

```
frozen-flask/frozen-flask-0.11/flask_frozen/__init__.py", line 287, in _build_one
    if not os.path.isdir(dirname):
  File "/usr/lib/python3.4/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf8' in position 25: ordinal not in range(128)
```

It seems to me that there are some issues with the UTF-8 support. I can bypass that error by utf-encoding the dirname but then other glitches arise.

**Comment by SimonSapin** [comment]
What does [`sys.getfilesystemencoding()`](https://docs.python.org/3/library/sys.html#sys.getfilesystemencoding) return for you? It should be UTF-8, but I suspect it’s not. I’d be surprised if this is related to English vs French in the locale.

**Comment by SimonSapin** [comment]
Well, the filesystem encoding *is* determined by Python based on locale-related environment variables. What I mean is that I’d be surprised if Frozen-Flask has code that assumes an English locale. The traceback looks more like it has code that expects the filesystem encoding to support some non-ASCII characters.

(By the way, use ```` ``` ```` on github to delimit code blocks.)

**Comment by oorestisime** [comment]
Ok so you are right, when i have LC_ALL set to fr_CH.UTF-8, python determines that the filesystem encoding is ascii. I am not sure why this happens

**Comment by oorestisime** [comment]
ok i fixed the issue by properly selecting my locale with dpkg-reconfigure locales ... sorry for bothering.

**Comment by SimonSapin** [comment]
No worries! Filesystem encoding in Python are tricky.
