### ISSUE TITLE
Frozen-Flask and Flask-Classy

### ISSUE THREAD

**Issue by Julien76** [SimonSapin/Frozen-Flask#54]
Hi,

I'm setting a website using Flask-Classy and Frozen-Flask, but I fail to understand how can i link the two:
How frozen-flask generator should be configure to work with flask-classy?

For example, I have this Flask-Classy view:

    class FooView(FlaskView):
        def bar(self, something):
            return render_template('bar.html', something=something)

My url is then:
 
    /foo/bar/<something>

How should I write the Frozen-Flask generator:
    
    @freezer.register_generator
    def XXX():
        for s in something_db:
            yield {'something': something}

I fail to name properly XXX. Of course I could try forcing flask-classy to use a defined endpoint, but I would  loose one of the advantage of flask-classy.

Thanks in advance for your help.

**Comment by SimonSapin** [comment]
I don’t know, I’ve never used Flask-Classy. Do you have an `app` object? What does `[rule.endpoint for rule in self.app.url_map.iter_rules()]` look like? Your generators can also `yield 'endpoint_name', {'key': 'value'}` so that their own name is irrelevant.

**Comment by Julien76** [comment]
Hi Simon,
I just realized that I never answered to you reply... very sorry about that. Your suggestion solved my problem. So I think I can close this issue.
Thanks again.
